# Copyright 2022 susatthi All rights reserved.
# Use of this source code is governed by a MIT license that can be
# found in the LICENSE file.

name: github_search
description: Search GitHub repositories.
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10+1
  flutter_riverpod: ^2.0.0-dev.9
  flutter_state_notifier: ^0.7.1
  flutter_svg: ^1.1.0
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.0.3
  go_router: ^3.1.1
  hexcolor: ^2.0.7
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  isar: ^3.0.0-dev.0
  isar_flutter_libs: ^3.0.0-dev.0
  json_annotation: ^4.5.0
  lottie: ^1.3.0
  markdown: ^5.0.0
  number_display: ^3.0.0
  path_provider: ^2.0.10
  photo_view: ^0.14.0
  roggle: ^0.2.1+1
  shimmer: ^2.0.0
  url_launcher: ^6.1.2
  visibility_detector: ^0.3.3

dev_dependencies:
  build_runner: ^2.1.11
  fast_i18n: ^5.12.6
  flutter_gen_runner: ^4.2.1
  flutter_launcher_icons:
    # v0.9.2 ではなく macOS と windows をサポートしている fork を利用する
    git: https://github.com/dirkbo/flutter_launcher_icons
  flutter_native_splash: ^2.2.2
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  golden_toolkit: ^0.13.0
  isar_generator: ^3.0.0-dev.1
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  path: ^1.8.1
  pedantic_mono: ^1.19.2
  sqflite_common_ffi: ^2.1.1

flutter:
  assets:
    - assets/images/
    - assets/lottie/
  fonts:
    - family: Murecho
      fonts:
        - asset: assets/fonts/Murecho/static/Murecho-Thin.ttf
          weight: 100
        - asset: assets/fonts/Murecho/static/Murecho-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Murecho/static/Murecho-Light.ttf
          weight: 300
        - asset: assets/fonts/Murecho/static/Murecho-Regular.ttf
          weight: 400
        - asset: assets/fonts/Murecho/static/Murecho-Medium.ttf
          weight: 500
        - asset: assets/fonts/Murecho/static/Murecho-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Murecho/static/Murecho-Bold.ttf
          weight: 700
        - asset: assets/fonts/Murecho/static/Murecho-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Murecho/static/Murecho-Black.ttf
          weight: 900
  uses-material-design: true

flutter_gen:
  output: lib/utils/assets/

flutter_icons:
  # flutter pub run flutter_launcher_icons:main
  android: 'ic_launcher'
  ios: true
  macos: true
  windows: true
  image_path: 'assets/images/icon.png'
  adaptive_icon_background: '#eeeeee'
  adaptive_icon_foreground: 'assets/images/icon_adaptive_foreground.png'

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove
  color: '#eeeeee'
  image: 'assets/images/splash.png'
  color_dark: '#262626'
  image_dark: 'assets/images/splash_dark.png'

  # Android12以上はAndroidOS側でアプリアイコンをスプラッシュ表示してしまうので以下の通り設定が必要
  android_12:
    image: 'assets/images/splash_android_12.png'
    icon_background_color: '#eeeeee'
    image_dark: 'assets/images/splash_android_12_dark.png'
    icon_background_color_dark: '#262626'
